[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;

$DATABASEDOTCOM_CLIENT_ID="3MVG9pe2TCoA1Pf6b.MWGLscN_7l51xXAF79OFZmjqfNPto3JohTujho1eWZErHffpBnRYVH8889zpruvUOp0"
$DATABASEDOTCOM_CLIENT_SECRET="D57E4EBC49CB0CACF946BAECD60514F3284FB917215C88667F79A679949B4D77"
$DATABASEDOTCOM_CLIENT_USERNAME="mushimaruko@gmail.com"
$DATABASEDOTCOM_CLIENT_AUTHENTICATE_PASSWORD="#42Mushi3"
$DATABASEDOTCOM_HOST="login.salesforce.com"

curl -s https://$DATABASEDOTCOM_HOST/services/oauth2/token -d "grant_type=password" -d "client_id=$DATABASEDOTCOM_CLIENT_ID" -d "client_secret=$DATABASEDOTCOM_CLIENT_SECRET" -d "username=$DATABASEDOTCOM_CLIENT_USERNAME" -d "password=$DATABASEDOTCOM_CLIENT_AUTHENTICATE_PASSWORD"
